def commands():
    print("Commands:\n")
    print("dashboard    - devices and network summary")
    print("network      - configure IP range and network interface")
    print("scan         - find and save all connected devices")
    print("tag          - assign name to untagged device")
    print("listen       - constantly repeat scan, alert about unknown devices")
    print("devices      - see tagged and untagged devices")
    print("rename       - change name of device or tag it by MAC address")
    print("forget       - make device unknown to ktotu")
    print("macs         - see only MAC addresses of tagged and untagged devices")
    print("help         - help page, you are here")
    print("commands     - commands list")
    print("about        - info about ktotu")
    print("quit         - close ktotu")