from constants import *

def print_help():
    print("Help:")
    print("\n0. How to use ktotu:")
    print("\n'ktotu: network' - You decide which network you want to monitor and tell the network interface and IP range to ktotu.")
    print("\n'ktotu: scan' - Then you find devices in your network. Now you know MAC addresses of connected devices.")
    print("In order to distinguish your devices from intruders, it's highly recommended to tag your devices.")
    print("\n'ktotu: rename' - Sometimes you can check MAC addresses of your devices by simply reading it in, for example, settings in smartphone.")
    print("If you know your smartphone's MAC address, you can assign the name using 'rename' command.")
    print("If your device is not visible on the list, connect your device to monitored network and run scan.")
    print("\n'ktotu: tag' - Alternatively you can run 'tag' command. It will perform scan for active devices. Then you decide which device's MAC address you want to discover.")
    print("You disconnect that device from network, write the name to ktotu and ktotu will know which device disappeared from network and assign the provided name to it.")
    print("This device is now tagged.")
    print("When you tag all your devices, you will fully benefit from using ktotu by monitoring your network.")
    print("\n'ktotu: listen' - start monitoring your network. You will be alerted about intruders and see currently connected devices to your network.")
    print("\n1. Glossary:\n")
    print("Types of devices:\n")
    print("tagged       - has a name and MAC address")
    print("untagged     - has MAC address")
    print("unknown      - never seen before")
    print("\nAny device is unknown at the beginning.")
    print("\n2. Commands:")
    print("\n> network")
    print("Configure IP range and interface which you want to monitor.")
    print("\n> dashboard")
    print("See devices and network summary. Press Enter to open dashboard.")
    print("\n> scan")
    print("Finds all devices connected to your network. Once ktotu finds a new one, it becomes untagged.")
    print("\n> tag")
    print("To recognize these devices, you can use tag command. Once you tag device, it becomes tagged and it's easier to track.")
    print("\n> listen")
    print("Constantly repeat scan, alert about unknown devices.")
    print("\n> devices")
    print("See tagged and untagged devices.")
    print("\n> macs")
    print("See only MAC addresses of tagged and untagged devices.")
    print("\n> forget")
    print("Make device unknown to ktotu if you want so.")
    print("\n> rename")
    print("Change name of device or tag it by MAC address.")
    print("\n> help")
    print("You are here")
    print("\n> about")
    print("Info about ktotu")
    print("\n> quit")
    print("Close ktotu")

    print("\n3. Manual:")
    print("\nYou can use ktotu in two ways:")
    print("\nInteractive - simply start program using 'ktotu' command as you did")
    print("Single command - type 'ktotu' with command that you want to execute and optionally with parameters. Example: 'ktotu scan' or 'ktotu f 2'")
    print("\nYou can type only first letter of command as well, for example 't' for 'tag' or 'r' for 'rename' command. 'd' is 'devices'")
    print("At any time press Enter to return to dashboard.")

    print("\n4. Technical description:\n")
    print("Devices and network data is stored in /home/{your_username}/%s" % user_files_directory_path)
    print("ktotu is installed in %s" % ktotu_path)
    print("Along with ktotu, there is mac_addresses_scanner in the same location")
    print("ktotu has symlink from %s" % ktotu_symlink_path)
    print("Performing scan requires sudo, in order to run "+ktotu_path+"/"+mac_addresses_scanner)

    print("\n5. Bug report:\n")
    print("Please report bugs in public repository. Current link will always be available on ktotu page - https://maczan.pl/ktotu")
    print("\n6. It's not yet complete:\n")
    print("ktotu is in early stage of development. There are lots of things that should be improved, like scanning time or graceful exit during scan.")
    print("I'm actively working on it after hours. Please be patient and kind if possible.")
    print("\nI hope you will benefit using ktotu.")